# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

baseURL = "https://preview-developer.espressif.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Espressif Developer Portal Preview"
theme = "blowfish"

# Keep English on top level
defaultContentLanguageInSubdir = false

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 0

buildDrafts = true
buildFuture = true

[deployment]
  [[deployment.targets]]
    name = 'preview'
    url = 's3://developer-portal-preview?region=ap-east-1&prefix=subdir/'
    exclude = "persist/**"

[pagination]
  pagerSize = 30

[imaging]
  anchor = 'Center'

[params.Author]
  name = "John Lee"
  image = "img/authors/espressif.png"
  bio = "Espressif Systems"
  links = [
    { "linkedin" = "https://www.linkedin.com/company/espressif-systems" },
    { "twitter" = "https://twitter.com/EspressifSystem" },
    { "instagram" = "https://www.instagram.com/espressif_systems_official" },
    { "medium" = "https://blog.espressif.com/" },
    { "github" = "https://github.com/espressif" },
    { "link" = "https://espressif.com/"},
  ]

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"
  platform = "platforms"
  soc = "socs"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
