# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Awesome"
#  weight = 10

#[[main]]
#  name = "Arduino"
#  parent = "Awesome"
#  pageRef = "pages/arduino"
#  weight = 10

#[[main]]
#  name = "ESP-IDF"
#  parent = "Awesome"
#  pageRef = "pages/esp-idf"
#  weight = 10

#[[main]]
#  name = "IDEs"
#  parent = "Awesome"
#  pageRef = "pages/ides"
#  weight = 10

#[[main]]
#  name = "Rust"
#  parent = "Awesome"
#  pageRef = "pages/rust"
#  weight = 10

#[[main]]
#  name = "NuttX"
#  parent = "Awesome"
#  pageRef = "pages/nuttx"
#  weight = 10

#[[main]]
#  name = "Zephyr"
#  parent = "Awesome"
#  pageRef = "pages/zephyr"
#  weight = 10

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 12

[[main]]
  name = "Workshops"
  pageRef = "workshops"
  weight = 13

[[main]]
  name = "Events"
  pageRef = "events"
  weight = 20

[[main]]
  name = "Products"
  weight = 25

[[main]]
  name = "Hardware"
  parent = "Products"
  pageRef = "hardware"
  weight = 25

[[main]]
  name = "Software"
  parent = "Products"
  pageRef = "software"
  weight = 25

[[main]]
  name = "Quick Links"
  weight = 30

[[main]]
  name = "Product Selector"
  parent = "Quick Links"
  url = "https://products.espressif.com/"
  weight = 30

[[main]]
  name = "Documents"
  parent = "Quick Links"
  url = "https://documentation.espressif.com/en/home"
  weight = 11

[[main]]
  name = "ESP32 Forum"
  parent = "Quick Links"
  url = "https://esp32.com"
  weight = 30

[[main]]
  name = "Reddit"
  parent = "Quick Links"
  url = "https://www.reddit.com/r/esp32/"
  weight = 30

[[main]]
  name = "Component Registry"
  parent = "Quick Links"
  url = "https://components.espressif.com/"
  weight = 30

[[main]]
  name = "DevCon"
  parent = "Quick Links"
  url = "https://devcon.espressif.com/"
  weight = 30

[[main]]
  name = "Espressif Site"
  parent = "Quick Links"
  url = "https://espressif.com"
  weight = 10

[[footer]]
  name = "About"
  pageRef = "pages/about"
  weight = 90

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Authors"
  pageRef = "authors"
  weight = 20

[[footer]]
  name = "Contribute"
  pageRef = "pages/contribution-guide"
  weight = 100

[[footer]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/espressif/developer-portal/"
  weight = 400
